
name: Deploying Springboot(War) to Tomcat on Azure Windows Server
on:
  push:
    branches:
      - main
  workflow_dispatch: 


jobs:
  build-springboot-app:
    name: Build Springboot Application
    runs-on: ubuntu-latest 
    steps:
    - name: Install Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Verify Java Version 
      run: java -version


    - name: Download the Code
      uses: actions/checkout@v3

    - name: Fix Permission Error
      run: chmod +x mvnw 

    - name: Build the Code
      run: ./mvnw package 

    - name: Rename WAR file
      run: mv ./target/apiservice-0.0.1-SNAPSHOT.war ./target/"${GITHUB_RUN_NUMBER}".war
    
    - name: Verify renamed
      run: ls -l target/*.war

    - name: Verify the Build is Created or Not
      run: ls -l target/*.war

    - name: Deploy the Build to Tomcat
      uses: mdallasanta/ssh-scp-deploy@v1.2.0
      with:
        local: 'target/apiservice-0.0.1-SNAPSHOT.war'                                                 
        remote: 'C:\Program Files\Apache Software Foundation\Tomcat 10.0\webapps\'                                               
        host: ${{secrets.HOST}}                                  
        user: ${{secrets.USER}}
        password: ${{secrets.PASSWORD}}
        pre_upload: echo "This will be executed before the upload!"
        post_upload: echo "This will be executed after the upload!"
        ssh_options: -o StrictHostKeyChecking=no
        scp_options: -v

        # ploo


  






